### PR TITLE
Add ImGui Dialogs

### PR DESCRIPTION
**Pull request by time-killer-games**
OpenNBS-Light

OpenNBS-Dark

**Download pre-built binaries for Windows, macOS, and Linux here: [[GITHUB RELEASE]](https://github.com/time-killer-games/OpenNoteBlockStudio/releases/tag/v0.0.0.0)**

### CODE REVIEW

**Comment by time-killer-games** [comment]
the non-file dialogs (show_message(), show_question(), and show_question_ext()) flicker their graphics context back in forth from drawing their content to drawing all solid black. This has now been fixed with my libfiledialogs extension but i still need to commit those fixes to this repository. Please be patient and don't merge this until i have done so.

**Comment by charlie-sans** [comment]
hey time! would you like me to build them for windows?.

**Comment by time-killer-games** [comment]
> hey time! would you like me to build them for windows?.

Sure! Thank you! 

Source code here:

https://github.com/time-killer-games/libfiledialogs

Requires Visual Studio 2019 or later.

**Comment by charlie-sans** [comment]
i have visual studio 2022. could you also link to instructions on how to build using visual studio. as i main vscode and i have never once built for windows

**Comment by time-killer-games** [comment]
1) File -> Open. Select *.sln File.
2) Select "Debug" Dropdown Box and change it to Release
3) Build solution.
4) Select "x86" Dropdown Box and change it to x64
5) Build solution.

I can't remember whether onbs relies on an older version of gms or not which is why i need both x86 and x64 dll to play it safe and make sure i have what i need. But i only need one or the other, not sure which/ I'll find out from Ben.

**Comment by time-killer-games** [comment]
also it's not the dll i need, actually its the exe it builds, for clarification.

**Comment by time-killer-games** [comment]
@charlie-sans It's not the dll i need, actually it's the exe it builds, for clarification.
1) File -> Open. Select *.sln File. It is in `libfiledialogs/filedialogs/filedialogs.sln`.
2) Select "Debug" Dropdown Box and change it to Release, (unless it's already set to Release).
3) Select "x86" Dropdown Box and change it to x64, (unless it's already set to x64).
4) Build solution. The file wll be in `libfiledialogs/filedialogs/x64/Release`.

**Comment by time-killer-games** [comment]
@Bentroen @chenxi050402 this one should be ready for review, and if you find any issues i still haven't noticed, please let me know!

**Comment by charlie-sans** [comment]
The file dialogues for Windows are also built by the help of me. I thank
you for letting me be of assistance.

**Pull request merged**
