### PR TITLE
Update Minecraft Wiki links to new domain

### PR DESCRIPTION
**Pull request by Spongecade**
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all URLs accordingly.

### CODE REVIEW

**Review by encode42 — CHANGES_REQUESTED** [review]
Looks like a minecraftwiki link was missed [here](https://github.com/OpenNBS/OpenNoteBlockStudio/blob/45f35ea193268fb541c1297d0b656f4964339d97/scripts/open_schematic/open_schematic.gml#L3), otherwise LGTM!

**Comment by Spongecade** [comment]
You've just introduced a flood of other pr's...
Thanks though

**Review by chenxi050402 — CHANGES_REQUESTED** [review]
Please change all data values URL to https://minecraft.wiki/w/Java_Edition_data_values/Pre-flattening
It starts with https:// instead of http:// and it should point to the pre-flattening data values

**Comment by Spongecade** [comment]
On it!

**Comment by Spongecade** [comment]
Sorry for the commit mess! Should be good to go now though!

**Comment by Spongecade** [comment]
Ok that was really the last one :/

**Comment by chenxi050402** [comment]
Looks good! Merging.

**Pull request merged**
